#####################################
##### CONFIG FOR NORMAL KFOLD CV ####
#####################################

# if set num_folds < 1,
# prog would only train a single model
# rather than use cross validation 
kfold_setting:
  num_folds: 8
  stratified: True
  random_state: 1024

lgb_model_param:
  n_jobs: -1
  verbose: -1

  n_estimators: 5000
  learning_rate: 0.008
  
  num_leaves: 43
  max_depth: -1
  
  colsample_bytree: 0.095
  subsample: 0.85
  subsample_freq: 3
  
  reg_alpha: 5
  reg_lambda: 0.5
  
  min_split_gain: 0.035
  min_child_weight: 45
  min_child_samples: 20
  # scale_pos_weight: 1

xgb_model_param:
  n_jobs: -1
  verbose: -1

  n_estimators: 3000
  learning_rate: 0.015
  
  max_depth: 6
  
  colsample_bytree: 0.095
  subsample: 0.85
  
  reg_alpha: 5
  reg_lambda: 0.5
  
  min_split_gain: 0.035
  min_child_weight: 45
  min_child_samples: 20
  # scale_pos_weight: 1