# input data filepath
input:
  train_filepath:                 ./input/application_train.csv
  test_filepath:                  ./input/application_test.csv
  bureau_balance_filepath:        ./input/bureau_balance.csv
  bureau_filepath:                ./input/bureau.csv
  credit_card_balance_filepath:   ./input/credit_card_balance.csv
  installments_payments_filepath: ./input/installments_payments.csv
  POS_CASH_balance_filepath:      ./input/POS_CASH_balance.csv
  previous_application_filepath:  ./input/previous_application.csv

# workspace
workspace: ./workdir

# model setting, only valid in training mode
kfold_setting:
  num_folds: 5
  stratified: True
  seed: Null
  model_param:
    n_estimator: 3000
    learning_rate: 0.01