#####################################
##### CONFIG FOR NORMAL KFOLD CV ####
#####################################

# if set num_folds < 1,
# prog would only train a single model
# rather than use cross validation 
kfold_setting:
  num_folds: 6
  stratified: True
  random_state: 1024

############
## LGB BOOST
############

model_param:
  n_jobs: -1
  verbose: -1

  n_estimators: 8000
  learning_rate: 0.0085
  
  num_leaves: 43
  max_depth: -1
  
  colsample_bytree: 0.085
  subsample: 0.80
  subsample_freq: 3
  
  reg_alpha: 5
  reg_lambda: 0.5
  
  min_split_gain: 0.045
  min_child_weight: 45
  min_child_samples: 20
  # scale_pos_weight: 1