####################################
### CONFIG FOR GRID PARAM SEARCH ###
####################################

num_folds: 5
stratified: True
seed: 2018
param_grid:
  n_estimators: 3000
  learning_rate: 0.01
  num_leaves:
    - 31
    - 63
    - 127
    - 255
    # - 511
    # - 1023
  colsample_bytree:
    - 0.1
    # - 0.15
    # - 0.25
    # - 0.3
    # - 0.5 
    # - 0.8
    # - 0.9
    # - 1.0
  max_depth:
    - -1
  #   - 8
  #   - 10
  #   - 12
  #   - 15
  # reg_alpha:
    - 0.1
  #   - 1
  #   - 2
  #   - 5
  #   - 10
  # reg_lambda:
    - 0.1
  #   - 0.5
  #   - 1
  #   - 2
  #   - 5
  #   - 10
  # min_split_gain:
  #   - 0.01
  #   - 0.05
  #   - 0.1
  #   - 0.5
  #   - 1
  #   - 10
  # min_child_weight:
  #   - 10
  #   - 40
  #   - 70 
  #   - 100