####################################
### CONFIG FOR GRID PARAM SEARCH ###
####################################

kfold_setting:
  num_folds: 5
  stratified: True
  random_state: 2018

param_grid:
  n_jobs: 16
  random_state: 2018
  n_estimators: 1800
  learning_rate: 0.02
  max_depth: -1

  num_leaves:
    - 43

  subsample: 
    - 0.85
    - 0.75
  subsample_freq: 
    - 3
  colsample_bytree:
    - 0.1
    - 0.12
    - 0.14
    # - 0.8
    # - 0.9
    # - 1.0

  reg_alpha:
    - 0.04
  #   - 1
  #   - 2
  #   - 5
  #   - 10
  reg_lambda:
    - 0.073
  #   - 0.5
  #   - 1
  #   - 2
  #   - 5
  #   - 10

  min_split_gain:
    - 0.0222415
  #   - 0.05
  #   - 0.1
  #   - 0.5
  #   - 1
  #   - 10
  min_child_weight:
    - 45
  min_child_samples: 
    - 20