####################################
### CONFIG FOR GRID PARAM SEARCH ###
####################################

num_folds: 5
stratified: True
seed: 2018
param_grid:
  n_jobs: 16

  n_estimators: 2000
  learning_rate: 0.02
  max_depth: -1

  num_leaves:
    - 23
    - 27
    - 31
    - 35
    - 39
    - 43

  subsample: 
    - 0.8715623
  subsample_freq: 
    - 3
  colsample_bytree:
    - 0.1
    # - 0.15
    # - 0.25
    # - 0.3
    # - 0.5 
    # - 0.8
    # - 0.9
    # - 1.0

  reg_alpha:
    - 0.04
  #   - 1
  #   - 2
  #   - 5
  #   - 10
  reg_lambda:
    - 0.073
  #   - 0.5
  #   - 1
  #   - 2
  #   - 5
  #   - 10

  min_split_gain:
    - 0.0222415
  #   - 0.05
  #   - 0.1
  #   - 0.5
  #   - 1
  #   - 10
  min_child_weight:
  #   - 10
    - 40
  #   - 70 
  #   - 100
  min_child_samples: 
    - 20